image:
- Visual Studio 2015
- Visual Studio 2017
- Visual Studio 2019

init:
- ps: (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full").Release

build:
  project: LocaleNetFxTest.sln

test_script:
- bin\Debug\LocaleNetFxTest.exe

- rd /q /s Properties
- rd /q /s bin
- rd /q /s obj
- del LocaleNetFxTest.csproj
- dotnet run LocaleNetFxTestCore.csproj